#!/bin/bash 

SCRIPTDIR=$(dirname -- "$(readlink "$BASH_SOURCE" || echo $BASH_SOURCE)")
# echo SCRIPTDIR: $SCRIPTDIR

pid=$1
freq=${2:-50}
time=${3:-30}

function process_stackshots()
{
    if [[ -f stackshots-$pid.out ]] ; then
        stackshots=`cat stackshots-$pid.out`
        echo $stackshots
        mkdir -p ${stackshots%.*}
        $SCRIPTDIR/foldstackshots.sh $stackshots
    fi
}

function ctrl_c() {
    if [[ -f stackshots.pid ]]; then
        trap INT
        sleep 1
        process_stackshots
    fi
}

trap ctrl_c INT
sudo -E $SCRIPTDIR/stackshots.lua $pid -f $freq -t $time
process_stackshots